apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alessandrotaufer/demo-deployment.git
    targetRevision: HEAD
    path: apps/httpbin
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-httpbin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
