apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-generator
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/AlessandroTaufer/gitops-playground.git
        revision: main
        directories:
          - path: apps/*/envs/*
  template:
    metadata:
      name: "{{ index .path.segments 1 }}-{{ .path.basename }}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AlessandroTaufer/gitops-playground.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ index .path.segments 1 }}-{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
