apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-generator
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: podinfo-dev
            namespace: podinfo-dev
            values:
              replicaCount: "1"
              uiMessage: "Hello from dev"
          - name: podinfo-staging
            namespace: podinfo-staging
            values:
              replicaCount: "2"
              uiMessage: "Hello from staging"
          - name: podinfo-prod
            namespace: podinfo-prod
            values:
              replicaCount: "3"
              uiMessage: "Hello from prod"
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://stefanprodan.github.io/podinfo
        chart: podinfo
        targetRevision: 6.*
        helm:
          valuesObject:
            replicaCount: "{{ .values.replicaCount }}"
            ui:
              message: "{{ .values.uiMessage }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
